### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by thijsterlouw** [ngerakines/mochevent#1]
gcc -I /usr/local/lib/erlang/erts-5.7.2/include -I /usr/local/lib/erlang/lib/erl_interface-3.6.2/include -L/usr/local/lib/erlang/lib/erl_interface-3.6.2/lib/ -Wall -fPIC -I./ -g -O2 -DHAVE_CONFIG_H  -c mocheventcnode.c
mocheventcnode.c: In function 'request_handler':
mocheventcnode.c:109: warning: implicit declaration of function 'TAILQ_FOREACH'
mocheventcnode.c:109: error: 'next' undeclared (first use in this function)
mocheventcnode.c:109: error: (Each undeclared identifier is reported only once
mocheventcnode.c:109: error: for each function it appears in.)
mocheventcnode.c:109: error: expected ';' before '{' token
mocheventcnode.c:124: error: 'arr' undeclared (first use in this function)
mocheventcnode.c:130: error: 'emsg2' undeclared (first use in this function)
mocheventcnode.c:106: warning: unused variable 'nalloc'

**Comment by thijsterlouw** [comment]
I downloaded queue.h from this location and included it:
http://www.openbsd.org/cgi-bin/cvsweb/~checkout~/src/sys/sys/queue.h?rev=1.32&content-type=text/plain

**Comment by ngerakines** [comment]
What version of libevent do you have installed?

**Comment by thijsterlouw** [comment]
I'm running Linux (which explains my old queue.h) and I installed the newest version of libevent (1.4.12). After adding queue.h from BSD, most errors went away, except for the one about 'next'

**Comment by ngerakines** [comment]
You'll need libevent 2.0+. I'll make a note to document that.

**Comment by thijsterlouw** [comment]
thanks, i'll try it immediately :)

**Comment by thijsterlouw** [comment]
we changed the makefile and added queue.h from libevent2 and installed libevent2, now it works:

Makefile we use:

---

ERL_DIR=$(shell erl -noshell -eval 'io:format("~s~n", [code:root_dir()])' -s erlang halt)
EI_DIR=$(shell erl -noshell -eval 'io:format("~s~n", [code:lib_dir("erl_interface")])' -s erlang halt)
EI_INC_DIR= -I $(ERL_DIR)/usr/include -I $(EI_DIR)/include
LDFLAGS=-fpic -L $(EI_DIR)/lib -L $(ERL_DIR)/usr/lib -levent_core -levent_extra -levent_pthreads  -lerl_interface -lei -lpthre
ad

PRIV_DIR=../priv
all: $(PRIV_DIR)/mochevent
$(PRIV_DIR)/mochevent: mocheventcnode.c
        @mkdir -p $(PRIV_DIR)
        gcc -Wall $(CFLAGS) $(EI_INC_DIR) -I ../include mocheventcnode.c -o $(PRIV_DIR)/mochevent $(LDFLAGS) 
clean: 
        @rm -rf $(PRIV_DIR)/mochevent
