### ISSUE TITLE
Potential issue thread-safety in mochevent.c

### ISSUE THREAD

**Issue by thijsterlouw** [ngerakines/mochevent#2]
Hi ngerakines,

I think in file mochevent/c/mocheventcnode.c on line 213
evhttp_add_header(clients[reqid]->output_headers, key, value);
is not thread-safe, because the main-thread can also update clients[reqid] via the request_handler on line 152 ?

Ps, I'm new to libevent / pthreads, so perhaps I didn't understand it correctly.

**Comment by ngerakines** [comment]
Adding pthread mutex lock/unlock calls to header modifications at 213. Closed by 2de0916ea6e14234036b24d623fbc15a5d82d21a.
